name: MMGlobalExchanges
version: '${project.version}'
main: xycm.momo.mmglobalexchanges.MMGlobalExchanges
author: "XY_Momo"
softdepend:
  - PlaceholderAPI
commands:
  MMGlobalExchanges:
    aliases:
      - "mmge"
    description: "全球交易"
    usage: "/mmge"