# 插件发送消息最前面的占位符
placeholder: "§e§l全球交易 §f>>> "

### 提示信息配置
# 提示信息开关(默认为关，提示信息在左下角聊天栏内，开启则显示在界面中的纸的名字上)
info: false
# 上一选项为true才生效，提示信息延时消失时间，上架记录下架提示，邮箱手动收取提示，主界面提示(单位: tick = 0.05s)
info_delay: 40
###

# 玩家扣钱指令
sub_money: "eco take <player> <price>"

# 玩家加钱指令
add_money: "eco give <player> <price>"

# 黑名单匹配模式
black_match:
  # 有name、lore和name-lore三种
  # name为模糊匹配名字
  # lore为模糊匹配对应词条
  # name-lore为模糊匹配其一即可
  mode: "name-lore"
  # 如果模式为lore则匹配物品的lore，数字为lore的索引
  lore: 0

# 物品显示名黑名单列表(模糊匹配)
black_name_list:
#  - "物品显示名(原版物品不包括)"
# 物品词条黑名单列表(模糊匹配)
black_lore_list:
#  - "词条、词条部分"

###市场相关配置
# 市场税率
tax_rate: 0.05
# 市场界面名字(名字不能重复，否则功能会出问题)
market:
  name: "全球交易"
  search: "市场搜索界面"
  select: "市场选择物品界面"
  launch: "市场上架物品"
  confirm: "市场购买确认"
  personal:
    name: "市场个人信息"
    purchase: "市场个人信息购买记录"
    sell: "市场个人信息出售记录"
    launch: "市场个人信息上架记录"
    confirm: "市场个人信息下架确认"
    mail: "市场个人信息邮件"

# 市场界面显示物品最大数量([1, 45])
market_max: 20
# 市场个人信息购买记录显示物品最大数量([1, 45])
market_personal_purchase_max: 20
# 市场个人信息出售记录显示物品最大数量([1, 45])
market_personal_sell_max: 20
# 市场个人信息上架记录显示物品最大数量([1, 45])
market_personal_launch_max: 20
# 市场个人信息邮箱显示物品最大数量([1, 45])
market_personal_mail_max: 20
###

###黑市相关配置
# 黑市商品信息掩盖起始索引
black_market_hidden_index: 7
# 黑市界面名字(名字不能重复，否则功能会出问题)
black_market:
  name: "黑市交易"
  search: "黑市搜索界面"
  select: "黑市选择物品界面"
  launch: "黑市上架物品"
  confirm: "黑市购买确认"
  personal:
    name: "黑市个人信息"
    purchase: "黑市个人信息购买记录"
    sell: "黑市个人信息出售记录"
    launch: "黑市个人信息上架记录"
    confirm: "黑市个人信息下架确认"
    mail: "黑市个人信息邮件"

# 黑市界面显示物品最大数量([1, 45])
black_market_max: 20
# 黑市个人信息购买记录显示物品最大数量([1, 45])
black_market_personal_purchase_max: 20
# 黑市个人信息出售记录显示物品最大数量([1, 45])
black_market_personal_sell_max: 20
# 黑市个人信息上架记录显示物品最大数量([1, 45])
black_market_personal_launch_max: 20
# 黑市个人信息邮箱显示物品最大数量([1, 45])
black_market_personal_mail_max: 20
###